### ISSUE TITLE
authorizerdev with nextJS not working on 12.1.0 & vanillaJS

### ISSUE THREAD

**Issue by LuD1161** [authorizerdev/examples#3]
Hey @lakhansamani 👋 

Awesome work with this. I've been checking your youtube tutorial for integrating this in nextJS but that seems to be not working as expected ( perhaps some SDK changes, not sure ).

Here's the timestamp of the video : https://youtu.be/2GMxfI6WUb8?list=PLSQGbUjHc6bpaAgCiQPzNxiUPr7SkDAFR&t=675
The `login` button changes to `logout`. 

Though when I am trying, by cloning this repo and running the nextJS example, the `access_token` remains in the URL bar as a query parameter 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/17861054/198379449-3ce42e44-1b1e-48cf-b71f-ef48ff7ec224.png">

LMK, what next steps to follow.

Thanks. Regards.
A

**Comment by LuD1161** [comment]
Just checked the unpkg hosted library is returning 520 .
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/17861054/198578359-129fae8b-479a-4b48-a58d-625732f9f5c3.png">

**Comment by aggmoulik** [comment]
Hey @LuD1161 ,Thank you for the input. Will let you know about the solution.

**Comment by aggmoulik** [comment]
Hey, @LuD1161 I have tried but it is working for me with the same example.

**Comment by lakhansamani** [comment]
@LuD1161 I have verified it,
It is happening because from screenshot I can see that you are using `brave` browser which does not allow cross domain cookies, so from local host it will not allow setting cookie for `demo.authorizer.dev` for this you will need to use same domain.

For testing purpose consider using chrome there it works. Else you can set insecure cookies from dashboard till development and that should fix the problem.

Also, this is happening because we have callback redirect from social media login.

I am figuring out a way to fix this for social media on sdk level.

**Comment by lakhansamani** [comment]
For more info,

if you login into https://authorizer.dev it uses the same instance as of example, i.e.e `demo.authorizer.dev` and as you can see there it works seamlessly which is again nextjs app.

https://github.com/authorizerdev/authorizer.dev/blob/v3/components/Hero.tsx#L132

**Comment by LuD1161** [comment]
Hey @lakhansamani @aggmoulik 👋 

Thank you for looking into it 🙌 

1. I tried on firefox as well 🤔 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/17861054/198830950-7b99c9ef-8531-40ef-a291-0235484d632b.png">

With my config : 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/17861054/198830964-104dc5ab-82fc-4424-bf8f-357b893e8188.png">

2. I also have disabled the `secure` cookie option : 
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/17861054/198831015-a04d6e11-4161-4247-b169-567365276f56.png">


3. Tried on chrome as well 🤔 
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/17861054/198831037-113fd1f1-cf19-41cc-b573-924b24779035.png">

Still no luck.

**Comment by LuD1161** [comment]
I see some error with `graphql` 
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/17861054/198831252-2d8b573b-02a5-4386-82ee-89d207d6572b.png">

**Comment by lakhansamani** [comment]
@LuD1161 policy is same for firefox and brave. It works for me on chrome

<img width="1680" alt="Screenshot 2022-10-29 at 5 52 26 PM" src="https://user-images.githubusercontent.com/6964334/198831345-0a95895a-164e-4607-9caa-a5ae2cdede75.png">

**Comment by LuD1161** [comment]
Even for chrome it shows unauthorised 🤔 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/17861054/198831435-8f6f49a1-0864-497a-85dc-1b54ce1da959.png">

check the console error too

**Comment by lakhansamani** [comment]
Can you share `package.json` info, on which version of SDKs you are using.

Thanks

**Comment by LuD1161** [comment]
I've changed `next` version to `^12.1.0`, else on `latest` ( since recent next release ) it's failing.
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/17861054/198831509-bc15aa0b-7f15-47c7-89bb-15a8ac43308a.png">

**Comment by LuD1161** [comment]
```
		"@authorizerdev/authorizer-js": "1.1.0",
		"@authorizerdev/authorizer-react": "1.1.0",
```

**Comment by lakhansamani** [comment]
Interesting I tried with same version.
Can you try updating authorizer-react to 1.1.2 once.

Thanks

**Comment by lakhansamani** [comment]
Other option is you can try deploying your site on heroku and try.

**Comment by LuD1161** [comment]
It's the same for authorizer 1.1.2 😅 
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/17861054/198831836-c556e5bd-9f2f-47f4-ba5e-a0f62d204742.png">

**Comment by LuD1161** [comment]
I tried logging the `token` as well 🤔 
It shows `null`
![Uploading image.png…]()

**Comment by lakhansamani** [comment]
Okay let me try to debug more and reproduce it,
thanks for patience

**Comment by LuD1161** [comment]
Sure. LMK if you wanna hop on a all to debug this 🙌

**Comment by lakhansamani** [comment]
I am able to reproduce the issue with your instance. Checking out the heroku cookie strategy.
Seems heroku specific.

**Comment by lakhansamani** [comment]
@LuD1161 can you once enable secure cookies on your instance from dashboard
<img width="1680" alt="Screenshot 2022-10-29 at 6 31 23 PM" src="https://user-images.githubusercontent.com/6964334/198833036-502d3c66-8b54-4148-bee6-ac4cb2ca132f.png">

**Comment by LuD1161** [comment]
@lakhansamani done 🖐️

**Comment by LuD1161** [comment]
Seems to be working , after a weird redirection though 😄 
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/17861054/198833567-71e8e1e6-ec4e-4b0a-8d08-0013a0d7d603.png">

What was the issue 🤔 
Also how did you fix it on my instance 🤔

**Comment by lakhansamani** [comment]
@LuD1161 seems secure cookie + chrome combination was the issue ;-)
I did not do anything.

Once you configure right domain for app + authorizer instance it will work across all the browser.

**Comment by lakhansamani** [comment]
I would do something like

xyz.com -> main app (nextjs)
auth.xyz.com -> authorizer instance.

**Comment by LuD1161** [comment]
oh okay. so as of now, this works, right ?
secure cookies - 🔴  ( for brave and firefox )
and
secure cookies - 🟢  ( for chrome )

**Comment by lakhansamani** [comment]
Yes for local development,
But if you configure right domains,
secure cookies - 🟢 (for brave & firefox)

**Comment by LuD1161** [comment]
Thanks a lot 🙌 😄
